name: CI Workflow on Self-Hosted Runner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted  # This tells GitHub to run on the self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display a message
        run: echo "Running on the self-hosted runner!"

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      - name: Run a simple shell command
        run: |
          echo "This is a sample command executed on the self-hosted runner."
