name: .NET Build, Test, and NuGet Package on Self-Hosted Runner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: self-hosted  

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up .NET environment
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0' 
        env:
          DOTNET_INSTALL_DIR: $HOME/.dotnet

      # Step 3: Print a message
      - name: Print message
        run: |
          echo "Hello from self-hosted runner!"
          dotnet --version
          echo "Running .NET build and tests!"

      # Step 4: Restore NuGet packages
      - name: Restore NuGet packages
        run: dotnet restore  # This will restore NuGet packages defined in your .NET project

      # Step 5: Build the project
      - name: Build the project
        run: dotnet build --configuration Release

      # Step 6: Run tests
      - name: Run tests
        run: dotnet test --configuration Release

      # Step 7: Publish the build (optional, depends on your project)
      - name: Publish build artifacts
        run: dotnet publish --configuration Release --output ./output
